spring:
    application:
        name: cleevio
    datasource:
        url: jdbc:postgresql://localhost:5432/cleevio
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

ethereum:
    url: 'http://127.0.0.1:30303'